# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: 'Bot.Builder.Community.sln'
    configuration: '$(buildConfiguration)'
    version: '$(GitVersion.NuGetVersion)'
  condition: succeeded()

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: 'Bot.Builder.Community.sln'
    configuration: '$(buildConfiguration)'
    nobuild: true
  condition: succeeded()

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    projects: 'Bot.Builder.Community.sln'
    command: pack
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
    configuration: '$(buildConfiguration)'
    nobuild: true
  condition: succeeded()

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  condition: succeeded()
