# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'Bot.Builder.Community.sln'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: 'Bot.Builder.Community.sln'
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion
    arguments: "--configuration $(buildConfiguration)"

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: 'Bot.Builder.Community.sln'
    configuration: '$(buildConfiguration)'
    nobuild: true
  condition: succeeded()

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    projects: 'Bot.Builder.Community.sln'
    command: pack
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
    configuration: '$(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion
    nobuild: true
  condition: succeeded()

- task: PublishBuildArtifacts@1
  condition: succeeded()

- task: NuGetCommand@2
  displayName: 'Publish Develop Packages to Artifacts Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/packages/*.nupkg'
    publishVstsFeed: '$(ARTIFACT_FEED_ID)'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq('true', variables['FORCE_PUSH_NUGET'])))

- task: NuGetCommand@2
  displayName: 'Publish Master Packages to NuGet Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/packages/*.nupkg'
    publishVstsFeed: '$(ARTIFACT_FEED_ID)'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('true', variables['FORCE_PUSH_NUGET'])))

- task: KriefMikael.githubtools.GitHubTag.GitHubTag@1
  displayName: 'Tag Master Branch'
  inputs:
    githubEndpoint: BotBuilderCommunity
    tag: 'v$(GitVersion.NuGetVersion)'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('true', variables['FORCE_PUSH_NUGET'])))